<%@ page contentType="text/html; charset=UTF-8" %>
<%@ page import="java.sql.*" %>
<%@ include file="/WEB-INF/jspf/conexion.jspf" %>
<%@ include file="/WEB-INF/jspf/utilidades.jspf" %>
<% String tituloPagina = "Detalle de propiedad"; String ctx = request.getContextPath(); Integer idUsuarioSesion = (Integer) session.getAttribute("idUsuario"); String rolSesion = (String) session.getAttribute("rol"); String nombreSesion = (String) session.getAttribute("nombre"); int id = aEntero(request.getParameter("id"),0); Connection con=null; PreparedStatement ps=null; ResultSet rs=null; %>
<%@ include file="/WEB-INF/jspf/cabecera.jspf" %>
<% try { con=abrirConexion(); ps=con.prepareStatement("SELECT p.*,c.nombre ciudad,t.nombre tipo,i.nombre inmobiliaria FROM propiedad p INNER JOIN ciudad c ON c.id_ciudad=p.id_ciudad INNER JOIN tipo_propiedad t ON t.id_tipo=p.id_tipo INNER JOIN inmobiliaria i ON i.id_inmobiliaria=p.id_inmobiliaria WHERE p.id_propiedad=? AND p.activo=1"); ps.setInt(1,id); rs=ps.executeQuery(); if (rs.next()) { String titulo=rs.getString("titulo"); %>
<div class="row g-4"><div class="col-lg-7"><div class="bg-white p-3 shadow-sm"><h1 class="h2"><%= esc(titulo) %></h1><p class="text-muted"><%= esc(rs.getString("tipo")) %> · <%= esc(rs.getString("ciudad")) %></p><p><%= esc(rs.getString("descripcion")) %></p><dl class="row"><dt class="col-sm-4">Precio</dt><dd class="col-sm-8 fw-bold"><%= pesos(rs.getDouble("precio")) %></dd><dt class="col-sm-4">Área</dt><dd class="col-sm-8"><%= rs.getDouble("area") %> m²</dd><dt class="col-sm-4">Habitaciones</dt><dd class="col-sm-8"><%= rs.getInt("habitaciones") %></dd><dt class="col-sm-4">Baños</dt><dd class="col-sm-8"><%= rs.getInt("banos") %></dd><dt class="col-sm-4">Inmobiliaria</dt><dd class="col-sm-8"><%= esc(rs.getString("inmobiliaria")) %></dd></dl><h2 class="h5 mt-4">Características</h2><div class="d-flex flex-wrap gap-2"><% PreparedStatement pc=con.prepareStatement("SELECT c.nombre FROM propiedad_caracteristica x INNER JOIN caracteristica c ON c.id_caracteristica=x.id_caracteristica WHERE x.id_propiedad=? ORDER BY c.nombre"); pc.setInt(1,id); ResultSet rc=pc.executeQuery(); while(rc.next()) { %><span class="badge text-bg-light border"><i class="bi bi-check2"></i> <%= esc(rc.getString(1)) %></span><% } cerrar(rc,pc); %></div><h2 class="h5 mt-4">Galería</h2><div class="row g-2"><% PreparedStatement pi=con.prepareStatement("SELECT url,texto_alternativo FROM imagen_propiedad WHERE id_propiedad=? ORDER BY orden,id_imagen"); pi.setInt(1,id); ResultSet ri=pi.executeQuery(); while(ri.next()) { %><div class="col-6"><img class="img-fluid rounded property-image" src="<%= esc(ri.getString(1)) %>" alt="<%= esc(ri.getString(2)) %>"></div><% } cerrar(ri,pi); %></div></div></div><div class="col-lg-5"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">¿Te interesa?</h2><p class="text-muted">Inicia sesión para guardar favoritos, agendar una visita o radicar una solicitud.</p><% if ("CLIENTE".equals(rolSesion)) { %><a class="btn btn-primary w-100 mb-2" href="<%= ctx %>/cliente/agendar.jsp?id=<%= id %>"><i class="bi bi-calendar-plus"></i> Agendar visita</a><a class="btn btn-outline-primary w-100" href="<%= ctx %>/cliente/favorito.jsp?id=<%= id %>"><i class="bi bi-heart"></i> Guardar favorito</a><% } else if (idUsuarioSesion == null) { %><a class="btn btn-primary w-100" href="<%= ctx %>/login.jsp">Ingresar para continuar</a><% } %></div></div></div></div>
<% } else { %><div class="alert alert-warning">La propiedad no existe o ya no está disponible.</div><% } } catch(SQLException ex) { %><div class="alert alert-danger">No fue posible consultar el detalle.</div><% } finally { cerrar(rs,ps,con); } %>
<%@ include file="/WEB-INF/jspf/pie.jspf" %>