<%@ page contentType="text/html; charset=UTF-8" %>
<%@ page import="java.sql.*" %>
<%@ include file="/WEB-INF/jspf/conexion.jspf" %>
<%@ include file="/WEB-INF/jspf/utilidades.jspf" %>
<%
String tituloPagina = "Propiedades"; String ctx = request.getContextPath(); Integer idUsuarioSesion = (Integer) session.getAttribute("idUsuario"); String rolSesion = (String) session.getAttribute("rol"); String nombreSesion = (String) session.getAttribute("nombre");
String texto = request.getParameter("texto"); String ciudad = request.getParameter("ciudad"); String tipo = request.getParameter("tipo");
if (texto == null) texto = ""; if (ciudad == null) ciudad = ""; if (tipo == null) tipo = "";
Connection con = null; PreparedStatement ps = null; ResultSet rs = null; PreparedStatement opciones = null; ResultSet ciudades = null; ResultSet tipos = null;
%>
<%@ include file="/WEB-INF/jspf/cabecera.jspf" %>
<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h2 mb-1">Propiedades disponibles</h1><p class="text-muted mb-0">Filtra y encuentra un lugar que encaje contigo.</p></div></div>
<form class="card border-0 shadow-sm p-3 mb-4" method="get"><div class="row g-2"><div class="col-md-4"><label class="form-label">Buscar</label><input class="form-control" name="texto" value="<%= esc(texto) %>" placeholder="Título o dirección"></div><div class="col-md-3"><label class="form-label">Ciudad</label><select class="form-select" name="ciudad"><option value="">Todas</option><% try { con = abrirConexion(); opciones = con.prepareStatement("SELECT id_ciudad,nombre FROM ciudad WHERE activa=1 ORDER BY nombre"); ciudades = opciones.executeQuery(); while (ciudades.next()) { %><option value="<%= ciudades.getInt(1) %>" <%= String.valueOf(ciudades.getInt(1)).equals(ciudad) ? "selected" : "" %>><%= esc(ciudades.getString(2)) %></option><% } cerrar(ciudades,opciones); opciones = con.prepareStatement("SELECT id_tipo,nombre FROM tipo_propiedad WHERE activo=1 ORDER BY nombre"); tipos = opciones.executeQuery(); } catch (SQLException ex) { %><option value="">No disponible</option><% } %></select></div><div class="col-md-3"><label class="form-label">Tipo</label><select class="form-select" name="tipo"><option value="">Todos</option><% if (tipos != null) { while (tipos.next()) { %><option value="<%= tipos.getInt(1) %>" <%= String.valueOf(tipos.getInt(1)).equals(tipo) ? "selected" : "" %>><%= esc(tipos.getString(2)) %></option><% } } cerrar(tipos,opciones); %></select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100"><i class="bi bi-funnel"></i> Filtrar</button></div></div></form>
<div class="row g-4">
<% try { String sql = "SELECT p.id_propiedad,p.titulo,p.descripcion,p.precio,p.area,p.habitaciones,c.nombre ciudad,t.nombre tipo,COALESCE(MIN(i.url),'') imagen FROM propiedad p INNER JOIN ciudad c ON c.id_ciudad=p.id_ciudad INNER JOIN tipo_propiedad t ON t.id_tipo=p.id_tipo LEFT JOIN imagen_propiedad i ON i.id_propiedad=p.id_propiedad WHERE p.activo=1 AND p.estado='DISPONIBLE' AND (?='' OR p.titulo LIKE ? OR p.direccion LIKE ?) AND (?='' OR p.id_ciudad=?) AND (?='' OR p.id_tipo=?) GROUP BY p.id_propiedad ORDER BY p.creado_en DESC"; ps = con.prepareStatement(sql); ps.setString(1,texto); ps.setString(2,"%"+texto+"%"); ps.setString(3,"%"+texto+"%"); ps.setString(4,ciudad); ps.setString(5,ciudad); ps.setString(6,tipo); ps.setString(7,tipo); rs = ps.executeQuery(); while (rs.next()) { %>
<div class="col-md-6 col-xl-4"><article class="card property-card"><% if (!rs.getString("imagen").isEmpty()) { %><img class="card-img-top property-image" src="<%= esc(rs.getString("imagen")) %>" alt="<%= esc(rs.getString("titulo")) %>"><% } %><div class="card-body d-flex flex-column"><span class="small text-muted"><%= esc(rs.getString("tipo")) %> · <%= esc(rs.getString("ciudad")) %></span><h2 class="h5 mt-2"><%= esc(rs.getString("titulo")) %></h2><p class="text-muted small flex-grow-1"><%= esc(rs.getString("descripcion")) %></p><div class="fw-bold mb-3"><%= pesos(rs.getDouble("precio")) %></div><a class="btn btn-outline-primary" href="<%= ctx %>/detalle.jsp?id=<%= rs.getInt("id_propiedad") %>">Ver detalle</a></div></article></div>
<% } } catch (SQLException ex) { %><div class="col-12"><div class="alert alert-danger">No fue posible cargar el catálogo en este momento.</div></div><% } finally { cerrar(rs,ps,tipos,opciones,ciudades,con); } %>
</div>
<%@ include file="/WEB-INF/jspf/pie.jspf" %>